### ISSUE TITLE
Senzing logger output could be a JSON-lines file

### ISSUE THREAD

**Issue by roncewind** [Senzing/go-logging#24]
If we move:
- Date
- time
- location
fields into JSON section of the log message, then we could construct a JSON-lines file from our log message which would make it easily parse-able

**Comment by docktermj** [comment]
For line in file, something like:

```go
_, filename, line, _ := runtime.Caller(1)
```

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/go-logging/pull/29
