### ISSUE TITLE
Optionally write to log file instead of stdout

### ISSUE THREAD

**Issue by roncewind** [Senzing/go-logging#27]
When writing an interactive or user facing program, writing JSON based log files to standard out is problematic.  We should have a way for log messages to be written to a file instead of stdout for such programs.

**Comment by docktermj** [comment]
The golang `log`'s  SetOutput() would be used for this.  https://pkg.go.dev/log#SetOutput

So just like setting
```go
log.SetFlags(0)
```

To have the output go to STDERR and a file, it would be something like this:

```go
    aFile, err := os.Open("/path/to/a/logfile")
    log.SetOutput(io.Writer(aFile))
```

To have the output go to STDERR and a file, it would be something like this:

```go
    aFile, err := os.Open("/path/to/a/logfile")
    log.SetOutput(io.MultiWriter(os.Stderr, aFile))
```

**Comment by docktermj** [comment]
Pull request:

- https://github.com/Senzing/go-logging/pull/65
