### ISSUE TITLE
We need to have an externalized message structure.

### ISSUE THREAD

**Issue by roncewind** [Senzing/go-logging#45]
Once we log a message or create an error, the message and error are JSON strings.  We need to have something like `messageFormatSenzing` ([here](https://github.com/Senzing/go-logging/blob/114812ba3fc201ed03d8750cf01ea4c8078aa9f2/messageformat/messageformat_senzing.go#L23-L34)) externalized so that we can extract the text of the message if we want to show a user error or other information if we're building a log analyzer.

**Comment by docktermj** [comment]
Function done in `go-messaging` https://github.com/Senzing/go-messaging/issues/8
